# https://travis-ci.org/phoebe-project/phoebe2-docs

language: python

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install pandoc
  - pip install jupyter

script: |
  if [ "$TRAVIS_COMMIT_MESSAGE" != "updating .md and .py sources" ] && [ -n $GITHUB_API_KEY ]; then
    jupyter nbconvert --to python tutorials/*ipynb --output-dir=tutorials/py
    jupyter nbconvert --to markdown tutorials/*ipynb --ouput-dir=tutorials/md
    jupyter nbconvert --to python examples/*ipynb --output-dir=examples/py
    jupyter nbconvert --to markdown examples/*ipynb --ouput-dir=examples/md
    git -c user.name='travis' -c user.email='travis' commit -m 'updating .md and .py sources'
    git add tutorials/py/*
    git add tutorials/md/*
    git add examples/py/*
    git add examples/md/*
    git push -q -f https://kecnry:$GITHUB_API_KEY@github.com/phoebe-project/phoebe2-docs $TRAVIS_BRANCH
  fi
