# https://travis-ci.com/phoebe-project/phoebe2-docs

# NOTE: because we checkout the branch, we may not be at this EXACT commit,
# but rather at the latest.  So re-running a travis build on and old commit
# will still update using the latest sources in the branch.  This shouldn't
# be a problem - we have the builds set to autocancel if a new push occurs
# anyways.

language: python

os: linux
dist: trusty

before_install:
  - pip install jupyter

script: |
  if [ "$TRAVIS_COMMIT_MESSAGE" != "TRAVIS: updating ipynb->py sources" ] && [ -n $GITHUB_API_KEY ]; then
    git remote rm origin
    git remote add origin https://kecnry:${GITHUB_API_KEY}@github.com/phoebe-project/phoebe2-docs.git > /dev/null 2>&1
    git -c user.name='travis' -c user.email='travis'
    mkdir -p $TRAVIS_BRANCH/tutorials
    mkdir -p $TRAVIS_BRANCH/examples
    jupyter nbconvert --to python tutorials/*ipynb --output-dir=$TRAVIS_BRANCH/tutorials
    jupyter nbconvert --to python examples/*ipynb --output-dir=$TRAVIS_BRANCH/examples
    cp tutorials/*ipynb $TRAVIS_BRANCH/tutorials/
    cp examples/*ipynb $TRAVIS_BRANCH/examples/
    git add $TRAVIS_BRANCH/tutorials/*
    git add $TRAVIS_BRANCH/examples/*
    git checkout master
    git commit -m 'TRAVIS: updating ipynb->py sources'
    git push -q -f origin $TRAVIS_BRANCH > /dev/null 2>&1
  fi
