# https://travis-ci.com/phoebe-project/phoebe2-docs

# NOTE: because we checkout the branch, we may not be at this EXACT commit,
# but rather at the latest.  So re-running a travis build on and old commit
# will still update using the latest sources in the branch.  This shouldn't
# be a problem - we have the builds set to autocancel if a new push occurs
# anyways.

language: python

os: linux
dist: trusty

before_install:
  - pip install jupyter

script: |
  if [ "$TRAVIS_COMMIT_MESSAGE" != "TRAVIS: updating ipynb->py sources" ] && [ -n $GITHUB_API_KEY ]; then
    git clone --depth 1 git://github.com/phoebe-project/phoebe2-docs.git ../phoebe2-docs-master
    mkdir -p ../phoebe2-docs-master/$TRAVIS_BRANCH/tutorials
    mkdir -p ../phoebe2-docs-master/$TRAVIS_BRANCH/examples
    jupyter nbconvert --to python tutorials/*ipynb --output-dir=../phoebe2-docs-master/$TRAVIS_BRANCH/tutorials
    jupyter nbconvert --to python examples/*ipynb --output-dir=../phoebe2-docs-master/$TRAVIS_BRANCH/examples
    cp tutorials/*ipynb ../phoebe2-docs-master/$TRAVIS_BRANCH/tutorials/
    cp examples/*ipynb ../phoebe2-docs-master/$TRAVIS_BRANCH/examples/
    cd ../phoebe2-docs-master
    git -c user.name='travis' -c user.email='travis'
    git add $TRAVIS_BRANCH/tutorials/*
    git add $TRAVIS_BRANCH/examples/*
    git commit -m 'TRAVIS: updating ipynb->py sources'
    git push -q -f https://kecnry:$GITHUB_API_KEY@github.com/phoebe-project/phoebe2-docs master
  fi
